### ISSUE TITLE
macOS Big Sur兼容问题

### ISSUE THREAD

**Issue by iwind** [crabapples-h/navicat-keygen-tools#18]
安装了：
~~~
brew install libplist
~~~
之后仍然提示：
~~~
-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib \
  \
  \
  \
-lcrypto -lcapstone -lkeystone -lplist++ ./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/X64ImageInterpreter.cpp ./navicat-patcher/HelperIsResolvedTo.cpp ./navicat-patcher/HelperPrintMemory.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher
ld: library not found for -lplist++
~~~

**Comment by nemo1080** [comment]
我也遇到了，不是bigsur的问题，是brew安装的libplist版本太高，你得想办法安装低版本。不过，keygen对15.0.17以上的版本都失效了，然而bigsur支持的最低版本是15.0.21，所以，目前无解。

**Comment by fancey** [comment]
bigsur 有激活办法么，更新了直接不能用了旧的

**Comment by FubukiGO** [comment]
试试之前的回答 我也是bigsur 亲测可以编译
https://github.com/HeQuanX/navicat-keygen-tools/issues/3#issuecomment-664342882

**Comment by iwind** [comment]
> 试试之前的回答 我也是bigsur 亲测可以编译
> [#3 (comment)](https://github.com/HeQuanX/navicat-keygen-tools/issues/3#issuecomment-664342882)

使用修改为2.0的方法确实可以编译，但是navicat-patcher没有成功，输出：
~~~
./navicat-patcher  /Applications/Navicat\ Premium.app/
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

[*] Your Navicat version: 15.0.22

[-] PatchSolution0 ...... Omitted.
[-] PatchSolution1 ...... Omitted.
[-] PatchSolution2 ...... Omitted.
[-] Patch abort. None of PatchSolutions will be applied.
    Are you sure your Navicat has not been patched before?
~~~

**Comment by FubukiGO** [comment]
我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了

**Comment by iwind** [comment]
> 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了

同样最后下载了一个破解版本。

**Comment by cnote0** [comment]
> > 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了
> 
> 同样最后下载了一个破解版本。

求破解版下载地址

**Comment by MangoYou** [comment]
> 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了

求一个破解版地址

**Comment by FubukiGO** [comment]
> > 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了
> 
> 求一个破解版地址

留下邮箱我发你

**Comment by MangoYou** [comment]
> > > 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了
> > 
> > 
> > 求一个破解版地址
> 
> 留下邮箱我发你

1749806593@qq.com  谢谢

**Comment by FubukiGO** [comment]
> > > > 我执行的时候也有这个错误 放弃折腾了， 直接下了一个破解版装上了
> > > 
> > > 
> > > 求一个破解版地址
> > 
> > 
> > 留下邮箱我发你
> 
> [1749806593@qq.com](mailto:1749806593@qq.com) 谢谢

查收下

**Comment by greenstar2017** [comment]
jlegend2011@126.com 感谢

**Comment by mayjiangfei** [comment]
> 我执行的时候也有这个错误的摆脱折腾了，直接下一个破解版装上了

求一个破解版地址

**Comment by zhengyingsdu** [comment]
求破解版地址 谢谢～邮箱yingzhengsdu@163.com

**Comment by lquanyang** [comment]
求破解版地址 谢谢～邮箱 lquanyang@gmail.com
