### ISSUE TITLE
ubuntu20.04显示激活次数达到上限

### ISSUE THREAD

**Issue by chaotianjiao** [crabapples-h/navicat-keygen-tools#21]
你好～非常感谢您的仓库和贡献，我在进行激活时显示
![image](https://user-images.githubusercontent.com/42534375/100702526-c8d29e00-33dc-11eb-9f80-4998779a4007.png)
想问一下我的错误在那里～？
谢谢～～～～～～

**Comment by lpdswing** [comment]
直接下载release版,或者是没断网?

**Comment by chaotianjiao** [comment]
@lpdswing  没断网，解决了~,再次感谢~
