### ISSUE TITLE
navicat15.0.26执行./navicat-patcher /Applications/Navicat\ Premium.app/报错

### ISSUE THREAD

**Issue by scyCoder** [crabapples-h/navicat-keygen-tools#27]
***************************************************
*       Navicat Patcher by @DoubleLabyrinth       *
*                  Version: 4.0                   *
***************************************************

Press Enter to continue or Ctrl + C to abort.

[*] Your Navicat version: 15.0.26

[-] PatchSolution0 ...... Omitted.
[-] PatchSolution1 ...... Omitted.
[-] PatchSolution2 ...... Omitted.
[-] Patch abort. None of PatchSolutions will be applied.
    Are you sure your Navicat has not been patched before?

**Comment by yiyayamaya** [comment]
楼主请问怎么解决的？

**Comment by scyCoder** [comment]
> 楼主请问怎么解决的？

换个低版本的Navicat

**Comment by yiyayamaya** [comment]
> > 楼主请问怎么解决的？
> 
> 换个低版本的Navicat

好的 谢谢 那个recommended version是不是就行？

**Comment by scyCoder** [comment]
recommended version 这个我没有太注意是多少，我用的是12.1.27版本
