### ISSUE TITLE
rebuild failed! 

### ISSUE THREAD

**Issue by liangsqrt** [crabapples-h/navicat-keygen-tools#29]
i mistaked navicate mysql as premium. then i noticed this and re-download navicat prenium. when i want to run navicate-patcher again, it throw out error:

[-] Try to open libcc.so ... Not found!

[-] ./navicat-patcher/main.cpp:240 ->
    No patch applied. Patch abort!
    Hints: Are you sure your Navicat has not been patched/modified before?

how to reslove this? 

thank you very much!

**Comment by Declarcall** [comment]
You must run navicat premium first!
Then closed and then mount AppImage. then ...

**Comment by liangsqrt** [comment]
thanks
