### ISSUE TITLE
linux 最新版 15.0.19 会报错  terminate called without an active exception

### ISSUE THREAD

**Issue by FlyInWind1** [crabapples-h/navicat-keygen-tools#7]
Press ENTER to continue or Ctrl + C to abort.

[+] Try to open libcc.so ... Ok!

terminate called without an active exception
[1]    116740 abort      sudo  /opt/navicat15-premium-cs

**Comment by daniel-chris-lucas** [comment]
I'm getting a similar output with navicat 15.0.19:

```
$ ./bin/navicat-patcher ~/Downloads/navicat15-premium-en-patched 
**********************************************************
*       Navicat Patcher (Linux) by @DoubleLabyrinth      *
*                  Version: 1.0                          *
**********************************************************

Press ENTER to continue or Ctrl + C to abort.

[+] Try to open libcc.so ... Ok!

terminate called without an active exception
[1]    15348 abort (core dumped)  ./bin/navicat-patcher ~/Downloads/navicat15-premium-en-patched
```

**Comment by alvarosdev** [comment]
Same error here
```
**********************************************************
*       Navicat Patcher (Linux) by @DoubleLabyrinth      *
*                  Version: 1.0                          *
**********************************************************

Press ENTER to continue or Ctrl + C to abort.

[+] Try to open libcc.so ... Ok!

terminate called without an active exception
[1]    803 abort      sudo ./navicat-patcher ~/Escritorio/NavicatPatched

```

**Comment by tyghaykal** [comment]
same error, still stuck

**Comment by dreamdevil00** [comment]
Any updates?

**Comment by crabapples-h** [comment]
The latest version is not supported. It is recommended to use the supported version.
https://github.com/HeQuanX/navicat-keygen-tools/releases/tag/recommended

**Comment by tyghaykal** [comment]
> The latest version is not supported. It is recommended to use the supported version.
> https://github.com/HeQuanX/navicat-keygen-tools/releases/tag/recommended

can you provide english version ?

**Comment by crabapples-h** [comment]
> > The latest version is not supported. It is recommended to use the supported version.
> > https://github.com/HeQuanX/navicat-keygen-tools/releases/tag/recommended
> 
> can you provide english version ?

english version :
https://github.com/HeQuanX/navicat-keygen-tools/releases/tag/en

**Comment by andkab** [comment]
> The latest version is not supported. It is recommended to use the supported version.
> https://github.com/HeQuanX/navicat-keygen-tools/releases/tag/recommended

Can you provide russian version ?

**Comment by FlyInWind1** [comment]
15.0.20 居然可以patch了

**Comment by caifenglin** [comment]
Cannot find libcc.so what about this file
